import type { Component } from '@nordcraft/core/dist/component/component.types'
import { isPageComponent } from '@nordcraft/core/dist/component/isPageComponent'
import { safeCustomElementName } from '@nordcraft/core/dist/utils/customElements'
import { isDefined } from '@nordcraft/core/dist/utils/util'
import { takeIncludedComponents } from '@nordcraft/ssr/dist/components/utils'
import { removeTestData } from '@nordcraft/ssr/dist/rendering/testData'
import type { ProjectFilesWithCustomCode } from '@nordcraft/ssr/dist/utils/routes'
import { replaceTagInNodes } from '@nordcraft/ssr/dist/utils/tags'
import { getFontCssUrl } from '@nordcraft/ssr/src/rendering/fonts'
import { transformRelativePaths } from '@nordcraft/ssr/src/utils/media'
import type { Context } from 'hono'
import type { HonoEnv, HonoProject } from '../../hono'
import type { PageLoader } from '../loaders/types'

export const customElement =
  (pageLoader: PageLoader) =>
  async (
    ctx: Context<
      HonoEnv<
        HonoProject & {
          files: ProjectFilesWithCustomCode
          component: Component
        }
      >,
      '/.toddle/custom-element/:filename{.+.js}'
    >,
  ) => {
    const url = new URL(ctx.req.url)
    const project = ctx.var.project
    const errorResponse = (error: string, status: 403 | 404) =>
      ctx.json(
        {
          error,
          info: `Please see https://docs.nordcraft.com/components/export-a-component#export-as-web-component for more information on web component export`,
        },
        {
          headers: {
            // Allow all origins for error responses.
            // This is useful for debugging if a web component doesn't load/work
            'Access-Control-Allow-Origin': '*',
          },
          status,
        },
      )

    const componentName = ctx.req.param('filename').replace('.js', '')
    const files = await pageLoader({
      ctx,
      name: componentName,
    })
    if (!files) {
      return errorResponse('Component not found', 404)
    }
    const component = files.components?.[componentName]
    if (!component) {
      return errorResponse('Component not found', 404)
    }
    try {
      if (isPageComponent(component)) {
        return errorResponse(
          `Pages are not supported as custom elements, only components`,
          403,
        )
      }

      const themes = files.themes ?? {}
      const fontsToLoad = Object.values(themes).flatMap((theme) => theme.fonts)
      const includedComponents = takeIncludedComponents({
        root: component,
        projectComponents: files.components,
        packages: files.packages,
      })
      const customCodeSearchParams = new URLSearchParams([
        ['entry', component.name],
      ])
      const fontStylesheetUrl = getFontCssUrl({
        fonts: fontsToLoad,
        baseForAbsoluteUrls: url.origin,
      })
      const content = `/*
 * This file is autogenerated by Nordcraft and should not be edited manually.
 *
 * <${safeCustomElementName(component.name)} />
 *
 * Attributes:
 *
 * ${Object.entries(component.attributes ?? {})
   .map(([, attr]) => `- ${attr.name}`)
   .join('\n * ')}
 *
 * Events:
 *
 * ${Object.entries(component.events ?? {})
   .map(([, event]) => `- ${event.name}`)
   .join('\n * ')}
 */

import { defineComponents, loadCorePlugins } from '/_static/custom-element.main.esm.js';
${
  files.customCode
    ? `import { loadCustomCode, formulas, actions } from '/.toddle/custom-code.js?${customCodeSearchParams.toString()}';`
    : `\
const formulas = {};
const actions = {};`
}

${
  isDefined(fontStylesheetUrl)
    ? `
    // Font loading in shadow-dom is not supported widely, so we inject in <head>
    // Ideally, we would inject the stylesheet directly in the ToddleComponent,
    // but it appears it doesn't fetch the fonts - only the stylesheet
    // See https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements#referencing_external_styles
    const linkElem = document.createElement("link");
    linkElem.setAttribute("rel", "stylesheet");
    linkElem.setAttribute("href", "${fontStylesheetUrl.swap}");
    document.head.appendChild(linkElem);`
    : ''
}

// Global toddle object
const toddle = (() => {
  const legacyActions = {}
  const legacyFormulas = {}
  const argumentInputDataList = {}
  return {
    formulas,
    actions,
    errors:[],
    project:"${project.name}",
    branch:"main",
    commit:"unknown",
    registerAction: (name, handler) => {
      if (legacyActions[name]) {
        console.error('There already exists an action with the name ', name)
        return
      }
      legacyActions[name] = handler
    },
    getAction: (name) => legacyActions[name],
    registerFormula: (name,handler,getArgumentInputData) => {
      if (legacyFormulas[name]) {
        console.error('There already exists a formula with the name ', name)
        return
      }
      legacyFormulas[name] = handler
      if (getArgumentInputData) {
        argumentInputDataList[name] = getArgumentInputData
      }
    },
    getFormula: (name) => legacyFormulas[name],
    getCustomAction: (name, packageName) => {
      return actions[packageName ?? "${project.name}"]?.[name] ?? actions["${
        project.name
      }"]?.[name]
    },
    getCustomFormula: (name, packageName) => {
      return formulas[packageName ?? "${project.name}"]?.[name] ?? formulas["${
        project.name
      }"]?.[name]
    },
    getArgumentInputData: (formulaName,args,argIndex,data
    ) => argumentInputDataList[formulaName]?.(args, argIndex, data) || data,
    data: {},
    locationSignal: null,
    eventLog: [],
    pageState: {},
    env: {
      isServer: false,
      branchName: "main",
      request: undefined,
    }
  }
})();

// Load core plugin (actions and formulas)
loadCorePlugins(toddle);

${
  files.customCode
    ? `\
// Load project's custom actions and formulas
loadCustomCode();`
    : ''
}

// toddle.isEqual is required for some formulas to work. TODO: Remove this once they can consume from somewhere else.
if(!globalThis.toddle || !globalThis.toddle.isEqual) {
  globalThis.toddle = {
    isEqual: toddle.isEqual,
  }
}

// Define the custom element
defineComponents(${JSON.stringify([component.name])}, ${JSON.stringify({
        themes,
        components: includedComponents
          .map(replaceTagInNodes(safeCustomElementName(component.name), 'div'))
          .map(removeTestData)
          .map(transformRelativePaths(url.origin)),
      })}, toddle);
`
      ctx.header('Cache-Control', 'no-cache')
      ctx.header('Access-Control-Allow-Origin', '*')
      ctx.header('Content-Type', 'text/javascript')
      return ctx.body(content)
    } catch (e) {
      // eslint-disable-next-line no-console
      console.error(e)
      return errorResponse('404', 404)
    }
  }
