import type { ToddleInternals } from '@nordcraft/core/dist/types'
import type { Context, Handler } from 'hono'
import { nanoid } from 'nanoid'
import type { HonoEnv } from '../../hono'
import type { PageLoaderUrls } from '../loaders/types'
import { InMemoryCache } from '../utils/cache'

const pageStateCache = new InMemoryCache<string>({
  ttlSeconds: 60 * 60 * 10, // 10 hours
  swrSeconds: 60 * 60 * 10, // 10 hours
})

export const pageStateHandler: Handler<
  HonoEnv,
  '/.nordcraft/page-state/:renderId{.+.js}'
> = async (c) => {
  c.header('Content-Type', 'application/javascript')
  // Ensure the page state is not cached by the browser
  c.header('Cache-Control', 'no-cache')
  const timestamp = c.req.query('t')
  const cacheUrl = pageStateCacheUrl({
    renderId: c.req.param('renderId'),
    timestamp: timestamp ? parseInt(timestamp) : undefined,
  })
  const cacheKey = pageStateCacheKey({
    ctx: c,
    cacheUrl,
  })

  const pageState = pageStateCache.get(cacheKey.url)
  if (!pageState) {
    // eslint-disable-next-line no-console
    console.error(`Page state not found for key: ${cacheKey.url}`)
    return c.body(null, { status: 500 })
  }
  return c.body(pageState.value)
}

export const pageStateCacheKey = ({
  ctx,
  cacheUrl,
}: {
  ctx: Context<HonoEnv<any>>
  cacheUrl: string
}) => {
  const url = new URL(ctx.req.url)
  return new Request(`${url.origin}${cacheUrl}`)
}

export const pageStateCacheUrl = ({
  renderId,
  timestamp,
}: {
  renderId: string
  timestamp?: number
}) =>
  `/.nordcraft/page-state/${renderId.endsWith('.js') ? renderId : `${renderId}.js`}${timestamp ? `?t=${timestamp}` : ''}`

export const cachePageState = ({
  state,
  ctx,
  pageName,
  usesCustomCode,
  options,
}: {
  state: ToddleInternals
  ctx: Context<HonoEnv<any>>
  pageName: string
  usesCustomCode: boolean
  options: PageLoaderUrls
}) => {
  const renderId = nanoid(10)
  const timestamp = Date.now()
  const pageStateUrl = pageStateCacheUrl({ renderId, timestamp })
  const cacheKey = pageStateCacheKey({ ctx, cacheUrl: pageStateUrl })
  const customCodeUrl = usesCustomCode
    ? options.customCodeUrl(pageName)
    : undefined
  const js = `\
// This file is auto-generated by nordcraft. Do not edit directly.
import { initGlobalObject, createRoot } from '/_static/page.main.esm.js';
${
  usesCustomCode
    ? `import { loadCustomCode, formulas, actions } from '${customCodeUrl}';`
    : `\
const formulas = {};
const actions = {};`
}
window.__toddle = ${JSON.stringify(state)};
window.__toddle.components = [window.__toddle.component, ...window.__toddle.components];
initGlobalObject({formulas, actions});
${usesCustomCode ? 'loadCustomCode();' : ''}
createRoot(document.getElementById("App"));
  `

  // Store the cached data for 10 hours, which is long enough for the page to load
  // and request the page state, and also long enough for crawlers to visit after its scheduled
  pageStateCache.set(cacheKey.url, js)
  return { pageStateUrl, customCodeUrl }
}
