import { writeFileSync } from 'fs'
import type { ExportedHtmlElement } from '../types'

const init = () => {
  elements.forEach((element) => {
    const output: ExportedHtmlElement = {
      metadata: {
        description: `An HTML element representing the ${element} element.`,
        link: `https://developer.mozilla.org/en-US/docs/Web/HTML/Element/${element}`,
        aliases: [],
      },
      element: {
        type: 'nodes',
        source: 'catalog',
        nodes: {
          root: {
            tag: element,
            type: 'element',
            attrs: {},
            style: {},
            events: {},
            classes: {},
            children: [],
          },
        },
      },
    }
    writeFileSync(
      `./elements/${element}.ts`,
      `import type { ExportedHtmlElement } from '../../types'\n\nconst ${element}: ExportedHtmlElement = ${JSON.stringify(output, null, 2)}\nexport default ${element}\n`,
      'utf-8',
    )
  })
}

const elements = [
  'a',
  'abbr',
  'address',
  'area',
  'article',
  'aside',
  'audio',
  'b',
  'base',
  'bdi',
  'bdo',
  'blockquote',
  'body',
  'br',
  'button',
  'canvas',
  'caption',
  'cite',
  'code',
  'col',
  'colgroup',
  'data',
  'datalist',
  'dd',
  'del',
  'details',
  'dfn',
  'dialog',
  'div',
  'dl',
  'dt',
  'em',
  'embed',
  'fieldset',
  'figcaption',
  'figure',
  'footer',
  'form',
  'h1',
  'head',
  'header',
  'hgroup',
  'hr',
  'html',
  'i',
  'iframe',
  'img',
  'input',
  'ins',
  'kbd',
  'label',
  'legend',
  'li',
  'link',
  'main',
  'map',
  'mark',
  'menu',
  'meta',
  'meter',
  'nav',
  'noscript',
  'object',
  'ol',
  'optgroup',
  'option',
  'output',
  'p',
  'picture',
  'pre',
  'progress',
  'q',
  'rp',
  'rt',
  'ruby',
  's',
  'samp',
  'script',
  'search',
  'section',
  'select',
  'slot',
  'small',
  'source',
  'span',
  'strong',
  'style',
  'sub',
  'summary',
  'sup',
  'table',
  'tbody',
  'td',
  'template',
  'textarea',
  'tfoot',
  'th',
  'thead',
  'time',
  'title',
  'tr',
  'track',
  'u',
  'ul',
  'var',
  'video',
  'wbr',
]

init()
