name: Playwright Tests
# on: workflow_dispatch
on:
  push:
    paths:
      # Only run when files in the e2e package change
      - 'e2e/**'

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./e2e
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Store package.json
        run: echo "PACKAGE_JSON=$(jq -c . < package.json)" >> $GITHUB_ENV
      - name: Current Playwright Version debug
        run: echo '${{ fromJson(env.PACKAGE_JSON).devDependencies['@playwright/test'] }}'
      - name: Current Playwright Version
        run: echo 'PLAYWRIGHT_VERSION=${{ fromJson(env.PACKAGE_JSON).devDependencies['@playwright/test'] }}' >> $GITHUB_ENV
      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
      - name: Install Playwright Browsers
        run: bunx playwright install chrome --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      - name: Run Playwright tests
        run: bunx playwright test
        # TODO: report failures on Discord
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 5
