name: Playwright Tests
# on: workflow_dispatch
on:
  push:
    paths:
      # Only run when files in the e2e package change
      - 'e2e/**'

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./e2e
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Install Playwright Browsers
        run: bunx playwright install chrome --with-deps
      - name: Run Playwright tests
        run: bunx playwright test
        # TODO: report failures on Discord
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 5
